import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { compileBlacklist, scanProvenance } from '../src/index.ts';

const FIX = join(__dirname, 'fixtures');
const load = (name: string) => (existsSync(join(FIX, name)) ? new Uint8Array(readFileSync(join(FIX, name))) : null);

describe('provenance scanner on real Content Credentials files', () => {
  // genai-actions-v2.jpg: contentauth/c2pa-js-legacy test fixture (MIT). Photoshop generative fill:
  // the active manifest says compositeWithTrainedAlgorithmicMedia, an ingredient says trainedAlgorithmicMedia.
  it('reports a generative-fill composite as edited (badge), and reads terms exactly', () => {
    const bytes = load('genai-actions-v2.jpg');
    if (!bytes) return;
    const r = scanProvenance(bytes);
    expect(r.hasC2pa).toBe(true);
    expect(r.verdict).toBe('edited');
    expect(r.sourceTypes).toContain('compositeWithTrainedAlgorithmicMedia');
    expect(r.sourceTypes).toContain('trainedAlgorithmicMedia'); // the AI ingredient; the composite term wins
    for (const t of r.sourceTypes) expect(t).not.toMatch(/metadata/); // no CBOR over-read
  });
  // firefly-labradoodle.jpg: contentauth/verify-site e2e fixture (Apache-2.0). Fully generated by Adobe Firefly.
  it('reports a Firefly image as generated (hide)', () => {
    const bytes = load('firefly-labradoodle.jpg');
    if (!bytes) return;
    const r = scanProvenance(bytes);
    expect(r.hasC2pa).toBe(true);
    expect(r.verdict).toBe('generated');
    expect(r.sourceTypes).toEqual(['trainedAlgorithmicMedia']);
  });
  it('reports nothing for an ordinary file', () => {
    const bytes = new TextEncoder().encode('\x89PNG\r\n\x1a\n plain image bytes with no manifest at all');
    expect(scanProvenance(bytes)).toEqual({ verdict: 'none', hasC2pa: false, sourceTypes: [] });
  });
  it('honors the legacy Adobe assertion', () => {
    const bytes = new TextEncoder().encode('jumb c2pa.assertions com.adobe.generative-ai Adobe Firefly');
    expect(scanProvenance(bytes).verdict).toBe('generated');
  });
});

describe('uBlacklist matcher', () => {
  it('handles match patterns, plain domains, hosts lines, regex, and unblocks', () => {
    const m = compileBlacklist(['*://*.slopfarm.example/*', 'plain.example', '0.0.0.0 hostsfile.example', '/^https:\\/\\/news\\.example\\/ai-/', '@*://*.good.slopfarm.example/*', '# comment', '']);
    expect(m.blocks('https://www.slopfarm.example/post')).toBe(true);
    expect(m.blocks('https://good.slopfarm.example/post')).toBe(false);
    expect(m.blocks('https://sub.plain.example/')).toBe(true);
    expect(m.blocks('https://hostsfile.example/')).toBe(true);
    expect(m.blocks('https://news.example/ai-generated-story')).toBe(true);
    expect(m.blocks('https://news.example/real-story')).toBe(false);
    expect(m.size).toBe(4);
  });
});
